### ISSUE TITLE
Issues building ActiveRecord joins

### ISSUE THREAD

**Issue by jamesfacts** [jamesfacts/losing_brooklyn#1]
Hi guys,

I've run into some trouble creating a join query through ActiveRecord. I can run my join query just fine through the Postgres interface, but I'm getting hung up on the syntax in Rails. (I know, I know.)

I believe I need to set up associations in my model classes in order to use the ActiveRecord "joins" method, but my associations are not functioning. I think this is because I do not have a foreign / primary key between my two tables, but rather a column with the same name that should contain matching entries.

I've been referring to http://guides.rubyonrails.org/active_record_querying.html#joining-tables
and
http://guides.rubyonrails.org/association_basics.html

I understand this is a vague question — if I'm shooting too broad to receive useful help, please let me know.

@harimohanraj89 @WilliamfShaw @DrRobotmck @bigtone1284

**Comment by bigtone1284** [comment]
Yeah, a little bit broad.  

Please let us know more specifically what you are trying to do (which entities, which attributes).

Also, if the SQL join is working, please let us know what that working SQL query looks like.

**Comment by jamesfacts** [comment]
Sure, here's the SQL join query:
`SELECT * FROM demo_permits JOIN pluto_records ON demo_permits.address = pluto_records.address LIMIT 10;`

I want to match rows in a table of demolition permits against a table of information (Pluto Records)  for every address in Brooklyn. The column these two tables share in common is called "address."

This is my Pluto record:

```
class PlutoRecord < ActiveRecord::Base
	belongs_to :demo_permit, through: :address
end
```

and this is my demo permit model:

```
class DemoPermit < ActiveRecord::Base
	has_one :pluto_record, through: :address
end
```

Just a little lost...

**Comment by bigtone1284** [comment]
can you please push latest code?

**Comment by WilliamfShaw** [comment]
@jamesfacts have you tried using a .execute of your object?

.execute will take the raw sql
